name: Build Docker Images

on: [push, pull_request]
env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:

  build-multipaper-docker:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      name: Checkout repository

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true     

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io 
        username: MultiPaperK8s
        password: $GITHUB_TOKEN

    - name: Docker meta for MultiPaperK8s/multipaper-master
      id: multipaper-master-meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/MultiPaperK8s/multipaper-master

    - name: Build and push multipaper-master for ${{ env.TARGET_PLATFORMS }}
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.master
        platforms: ${{ env.TARGET_PLATFORMS }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.multipaper-master-meta.outputs.tags }}
        labels: ${{ steps.multipaper-master-meta.outputs.labels }}
        target: multipaper-master

    - name: Docker meta for MultiPaperK8s/multipaper
      id: multipaper-server-meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/MultiPaperK8s/multipaper

    - name: Build and push multipaper for ${{ env.TARGET_PLATFORMS }}
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.server
        platforms: ${{ env.TARGET_PLATFORMS }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.multipaper-server-meta.outputs.tags }}
        labels: ${{ steps.multipaper-server-meta.outputs.labels }}
        target: multipaper-server